### ISSUE TITLE
get_boundaries() error with Elliptical Mirror

### ISSUE THREAD

**Issue by moellep** [lucarebuffi/OASYS-SRW#10]
I created a Syned Mirror with an Ellipse boundary shape and hooked it up to an SRW Elliptical Mirror in OASYS. When selecting "Send Data" on the Syned Mirror, it causes a python error: 'NoneType' object has no attribute 'get_boundaries'.

**Comment by lucarebuffi** [comment]
It is something to fix, but you get confused. 

The boundary shape it the shape of the mirror when you are looking it from a top view. SRW elliptical mirror are actually cylinders with elliptical profile, and their boundary shape is rectangular.

**Comment by lucarebuffi** [comment]
fixed in SYNED 1.0.31
