### ISSUE TITLE
Syned position and SRW wavefront propagation distance

### ISSUE THREAD

**Issue by moellep** [lucarebuffi/OASYS-SRW#11]
After creating a Syned mirror and hooking it up to an SRW mirror, when I select a value for "Distance from previous Continuation Plane" on the syned mirror and select "Send Data", the SRW mirror uses that value. If the SRW Source has a propagation distance selected on the Wavefront Setting tab, I need to subtract that amount from the first element's position to have the element placed correctly. Possibly the "Send Data" on the syned element could adjust the first element's "Distance from previous Continuation Plane" by the source's propagation distance automatically?

**Comment by lucarebuffi** [comment]
You need to add the initial SRW slit to the syned system.  Both the source and the slit must be attached to the SRW source widget:

![Screen Shot 2020-08-20 at 3 39 17 PM](https://user-images.githubusercontent.com/6713598/90823318-52150780-e2fb-11ea-8e02-3f6ecc7e5bc9.png)
