### ISSUE TITLE
expoted h5 files with wavefront cannot be reimported

### ISSUE THREAD

**Issue by srio** [lucarebuffi/OASYS-SRW#13]
Just a small problem that should be easy to fix for you, not for me: 

When exporting the wf to a file, it cannot be reimported: 

![image](https://user-images.githubusercontent.com/502315/117118903-a250ce80-ad91-11eb-9b74-8ca64340f63a.png)

**Comment by lucarebuffi** [comment]
I found the problem , and I will gladly fix YOUR code. :D :D :D :D

![Screen Shot 2021-05-05 at 11 03 29 AM](https://user-images.githubusercontent.com/6713598/117172654-9f55de00-ad91-11eb-804d-49a4887a9a8d.png)

**Comment by lucarebuffi** [comment]
Fixed in 1.1.80
