### ISSUE TITLE
error analysis

### ISSUE THREAD

**Issue by yangym-IHEP** [lucarebuffi/OASYS-SRW#14]
Dear author,
I have been using OASYS-SRW to do error analysis for a beamline. However, there are two problems that I cannot handle.

The first problem is about "roll" displacement of a optical element. Right now, OASYS-SRW GUI only support horizontal/vertical shift/angle. I also check the class SRWLOptShift and SRWLOptAng and found the same problem. Is there any other way I can add the displacement of the roll angle, that is, the angle around the propagation direction of X-ray.

The second problem is about thickness error of CRL. Can I still follow the way below？
https://github.com/oasys-kit/ShadowOui/issues/213

Thanks a lot!

**Comment by lucarebuffi** [comment]
On my knowledge, there is no explicit Roll displacement in SRW. Maybe one can play with the orientation of the optical element: you can't do that from the OASYS interface (the only direction allowed are Up, Down, Left, Right), but if you convert the simulation into a script (Group SRW Native, Single Electron Script widget), you will see the direction versors explicitly. It's a little complicated and I never did that.

 You should ask the author (Oleg Chubar at BNL) directly.

About the thickness error profile you can plug the dedicated SYNED widget directly to the SRW CRL widget.
This is also true for absorbers 

![Screen Shot 2021-09-05 at 10 09 20 PM](https://user-images.githubusercontent.com/6713598/132155272-bea60ec1-3020-498f-9448-7b1d46844441.png)

![Screen Shot 2021-09-05 at 10 08 24 PM](https://user-images.githubusercontent.com/6713598/132155213-a48dc1ca-5593-4e53-ac16-a0d3916fe5b9.png)

![Screen Shot 2021-09-05 at 10 08 56 PM](https://user-images.githubusercontent.com/6713598/132155243-97cc6758-7d19-401d-b6c4-2237cef99b99.png)

**Comment by lucarebuffi** [comment]
The format of the input file is ASCII, CSV, 3 columns: (Horizontal coordinate, Vertical coordinate, Thickness error)

**Comment by lucarebuffi** [comment]
[thickness_example.txt](https://github.com/oasys-kit/OASYS-SRW/files/7113062/thickness_example.txt)

**Comment by lucarebuffi** [comment]
Again on the direction of the optical element, please check the OASYS School: 

https://github.com/oasys-kit/oasys_school/blob/master/second/slides/Introduction_to_SRW.pptx

and

https://github.com/oasys-kit/oasys_school/blob/master/second/slides/Introduction_to_OASYS-SRW.pptx

where you can find this:

![Screen Shot 2021-09-05 at 10 20 10 PM](https://user-images.githubusercontent.com/6713598/132156061-99e28060-bdce-441f-8c08-17ef4d582184.png)

Maybe is helpful. I repeat, better ask the author directly (In case, I wouldn't mention OASYS, because originally SRW is in script form)

**Comment by lucarebuffi** [comment]
Another thing: leave the issues in OPEN status, and let us close them.

**Comment by yangym-IHEP** [comment]
Thank you for your detailed reply. I'll try to follow your instruction and do the error analysis.
