### ISSUE TITLE
srw obstacle fails to receive syned beam stopper

### ISSUE THREAD

**Issue by srio** [lucarebuffi/OASYS-SRW#15]
I am upgrading a few things in syned and I just realised there is a bug when receiving data from this srw widget:

![image](https://user-images.githubusercontent.com/502315/144275302-2c513043-83f9-4fb5-9300-ca111252cf7d.png)

Cheers, Manolo

**Comment by lucarebuffi** [comment]
I'll fix it. Can I use the current version of SYNED to test it?

**Comment by lucarebuffi** [comment]
Fixed in OASYS1-SRW 1.1.89
