### ISSUE TITLE
Missing widget CRL in 'SRW Optical Elements' (along with all the others)

### ISSUE THREAD

**Issue by ronchm** [lucarebuffi/OASYS-SRW#17]
Dear Author,

My name is Mattia (from European XFEL) and I wanna validate the tests I carried out during my beamtimes also by using your software, besides Ansys. I have the feeling this is a basic question but I tried to solve by my own without success. I hope that this post can come in handy to some other beginners as well.

My beamtime configuration was roughly this: undulator + collimating CRL + focusing CRL + CRL sample. Also the last one is a CRL, I studied its thermal behaviour by hitting with our X-ray beam (by contact and no-contact methods).
I have put the undulator and now I was searching for the CRL in 'SRW Optical Elements'. I didn't find it, so my guess is that I need to play around with widgets.
Could you by chance give a hint to add them?
I have installed all the add-ons and my programming skills are extremely basic.

Thank you for your attention and time
Best regards
Mattia

**Comment by lucarebuffi** [comment]
The widget is here:

![Screenshot 2023-07-31 at 10 10 12 AM](https://github.com/oasys-kit/OASYS-SRW/assets/6713598/365194e9-7c57-44c9-b322-c53b28b9a318)

If you don't see them, it means you have issues in your installation. I guess you are in a Windows computer....
Please reinstall OASYS from scratch. If the automatic procedure (https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10) won't work, maybe try to follow the step-by-step procedure (link is in the instructions), so you can see if and where there is a problem.

**Comment by ronchm** [comment]
Thank you so much for the kind reply Luca, I actually did the step-by-step installation and I thought I was okay because I didn't clearly see any error message.
And yes, I saw the widget in the video on youtube.
I could also try the other way around and let you know :]

Thank you for your time and attention.
Best regards
Mattia

**Comment by lucarebuffi** [comment]
If you don't see the widgets, you should see an error message on the command prompt that is launching Oasys.
Please grab it and post it here

**Comment by ronchm** [comment]
![CaptureOasys](https://github.com/oasys-kit/OASYS-SRW/assets/141029755/e7513c0c-bbe2-4c09-8c9c-80b0b3bc6c10)

Now that I see more carefully there are several errors

**Comment by lucarebuffi** [comment]
xraylib is an external library that we do not manage. Something went wrong while installing it.

**Comment by lucarebuffi** [comment]
Join me here: https://us06web.zoom.us/j/5151892993?pwd=dk9YWlcxbWJ1bWdOclorSHhyM0dBZz09

**Comment by ronchm** [comment]
Thanks a bunch for your precious help Luca! 👍
