### ISSUE TITLE
negative focal length for ideal lens

### ISSUE THREAD

**Issue by wcgrizolli** [lucarebuffi/OASYS-SRW#2]
I'm trying to use the ideal lens to produce a collimated beam or to emulate a convex mirror. When I try to set the focal length to a negative value, I get the message:

> Horizontal Focal Length should be > 0

It seems to be a limitation of OASYS-SRW because SRW accepts negative focal length. I tested it by creating a simple beamline in OASYS with Gaussian source, ideal lens and screen. Then I exported the beamline to python script and ran it in an external terminal (that is, outside OASYS). In this script, I change the signal of the focal length, and SRW produces the right results.

**Comment by lucarebuffi** [comment]
Fixed in OASYS1-SRW 1.0.67
