### ISSUE TITLE
Minor issue in ow_srw_spectrum.py

### ISSUE THREAD

**Issue by maltissimo** [lucarebuffi/OASYS-SRW#3]
Hey Luca, 

sorry to bother you. While coding a widget which gets an input from SRW's undulator spectrum, I noticed that the exchange data object has 2 columns only, while the Source Spectrum widget has 4 plots, so I was expecting 5 columns (i.e. energy, spectral flux, spectral flux density, spectral power, cumulated power): 

Then I had a quick look at the code you have in "ow_srw_spectrum.py" of the Oasys-SRW copy,  and found that the "create_exchange_data" method actually outputs only 2 of the columns, energy and spectral flux I think, so there lies the justification for what I found.

I was therefore wondering if you think it could be useful to add spectral flux density, spectral power and cumulated power to the exchange data object.

Obviously, this is only minor, so please do leave it out for when you have time, and I will code my own widget accommodating for this, no dramas.

Thank you for your work. 

Ciao

Matteo

**Comment by lucarebuffi** [comment]
I added the new columns in OASYS1-SRW 1.1.4:

0 Energy
1 Flux Density (ME)
2 Spectral Flux Density (SE)
3 Power 
4 Cumulated Power

Thank you!
