### ISSUE TITLE
phase plots

### ISSUE THREAD

**Issue by wcgrizolli** [lucarebuffi/OASYS-SRW#4]
It is not an issue, it is more a request for a new feature.

It would be nice if the phase plots could unwrap the phase. Phase unwrapping can be tricky and results in bad graphs, so ideally this would be an option.

**Comment by lucarebuffi** [comment]
I apologize for taking such a long time to implement this modification. I used the numpy.unwrap function to do it.

**Comment by wcgrizolli** [comment]
Great! It worked beautifully!

But there was a problem: after I updated the SRW add-on, SRW was not loading in Orange.

I ran `./start_oasys__VE.sh` at the terminal, and watched for errors. It seems the library scikit-image was missing. You may want to include it in the script `prepare_installation_VE.sh`

In my case, I did `sudo pip install scikit-image` and it solved the problem

**Comment by lucarebuffi** [comment]
You're right. But it must be added as a requirement in the add-on setup.py file.

thank you!

**Comment by lucarebuffi** [comment]
See OASYS1-SRW 1.1.34
