### ISSUE TITLE
problem displaying sigma and pi?

### ISSUE THREAD

**Issue by srio** [lucarebuffi/OASYS-SRW#5]
I think there is a problem displaying the SRW sigma and pi components. For an standard undulator with vertical field, the total intensity of sigma must be larger than the pi. I get the opposite. Is that a problem of the labels?
![image](https://user-images.githubusercontent.com/502315/64461458-19602c00-d0b2-11e9-946a-6640c1c5e253.png)
![image](https://user-images.githubusercontent.com/502315/64461508-3dbc0880-d0b2-11e9-8d84-e60ef27339e9.png)

Cheers, M

**Comment by lucarebuffi** [comment]
I just released a new version that fixes the problem.

**Comment by lucarebuffi** [comment]
Give me 1 hour, I am finishing some details

**Comment by srio** [comment]
no hurry!

**Comment by lucarebuffi** [comment]
There was a problem in the calculation of sigmas and fwhms. Now the calculation is ok and homogeneous for the whole OASYS. And, indeed, the labels are inverted.
