### ISSUE TITLE
Use of SRW python script

### ISSUE THREAD

**Issue by wcgrizolli** [lucarebuffi/OASYS-SRW#8]
Hi all

When I export a beamline to an SRW python script, what is the right way to run the script (outside OASYS) in order to use the SRW libraries of OASYS?

I guess I need to load the VE or the conda enviroment, but I want to hear from you what is the recommended way.

**Comment by lucarebuffi** [comment]
Just use OASYS miniconda environment to run the script. (This is how I do it).
If you use a MAC, the command is the following:

/Applications/Oasys1.2.app/Contents/MacOS/PythonApp <script>.py
